# Generated by Django 5.1.3 on 2025-02-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventReg', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
