# Generated by Django 5.1.3 on 2025-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventReg', '0003_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
