# Generated by Django 5.1.3 on 2025-02-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
